---
- name: Update repo cache
  apt:
    update_cache: yes

- name: Upgrade Packages
  apt:
    upgrade: full

- name: Reboot
  reboot:
    reboot_timeout: 3600

- name: Start all exited docker containers
  command: docker restart $(docker ps -f "status=exited" -q)
